# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

jobs:
  - job: primary_code_validation_and_tests
    displayName: Primary code validation and tests

    pool:
      vmImage: 'vs2017-win2016'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    # - script: |
    #     git clone git@github.com:AndrewWilliamsonFluent/reviewers.storage.git ../reviewers.storage
    #   displayName: 'Checkout reviewers storage'

    - script: |
        node-dependencies-{{ checksum "package.json" }}
        node-dependencies-

    - script: |
        npm install
      displayName: 'npm install'

    - script: |
        npm run build
      displayName: 'npm build'